Prettier Formatting
EasyApp-RPI/EasyApp pull request #42
Opened 2023-10-08 01:00 UTC by Tripplenut

# Pull Request

## Description

I added prettier to the code base to help keep formatting consistent. I also added a workflow to make a workflow auto run and commit this formatting to all PRs and pushes to main.

The only relevant files to review are:
.prettierignore
.prettierrc.json
.github/workflows/prettier.yml

Closes #40 

## Type of change

- [ ] Bug fix (change which fixes an issue)
- [x] Enhancement (change which alters existing functionality)
- [ ] New feature (change which adds new functionality)
- [ ] This change requires a wiki/documentation update

## How Has This Been Tested?

I haven't been able to test the workflow and knowing how good I am with github actions there is a 99% chance the build fails.

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

Try to checkoff as much as possible if not everything!

2023-10-13 20:41 UTC, LeadFreeCandy commented
I think we should update the readme and describe how you can run the prettier workflow. There than that, LGTM!

2023-10-13 20:42 UTC, LeadFreeCandy requested changes
I think we should update the readme and describe how you can run the prettier workflow. There than that, LGTM!

2023-10-14 17:28 UTC, Tripplenut commented
> I think we should update the readme and describe how you can run the prettier workflow. There than that, LGTM!

Added a short paragraph about it in #41.

2023-10-17 20:18 UTC, LeadFreeCandy approved these changes

2023-10-17 20:18 UTC, merged